# TensorFlow

## Intro

In [49]:
#importing library
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
#create tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check tensor dimention
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant(
    [[10,7],
     [7,10]]
);
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#create another matrix specifing dtype parameter
another_matrix = tf.constant(
    [
        [10., 7.],
        [3., 2.],
        [8., 9.]
    ],
    dtype=tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [15]:
#create a tensor
tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [0, 1, 2]
        ],
        [
            [3, 4, 5],
            [6, 7, 8]
        ]

    ],
    dtype=tf.int16
)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int16, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]],

       [[3, 4, 5],
        [6, 7, 8]]], dtype=int16)>

In [16]:
tensor.ndim

3

In [17]:
#creating tensor with tf.Variable
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
#try to change tensor element using indexing
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [24]:
#try to change tensor unchangable
#unchangable_tensor[0] = 7
#unchangable_tensor[0].assign(7)

In [30]:
#create two random tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
print(random_1, random_2, random_1 == random_2, sep="\n")

tf.Tensor(
[[-0.75658023 -0.06854693  0.07595028 -1.2573844  -0.23193759 -1.8107857
   0.09988729 -0.5099865  -0.75358063 -0.5716628 ]
 [ 0.14807744 -0.23362993 -0.35227957  0.40621278 -1.0523509   1.2054598
   1.687449   -0.44629765 -2.341084    0.9900914 ]
 [-0.08763231 -0.63556796 -0.61617357 -1.9441465  -0.48293006 -0.5244748
  -1.0345329   1.3066902  -1.5184574  -0.45852086]
 [ 0.5714664  -1.5331721   0.45331386  1.1487608  -1.2659091  -0.47450116
   2.006022    0.28288034 -0.30288237 -1.4436511 ]], shape=(4, 10), dtype=float32)
tf.Tensor(
[[-0.75658023 -0.06854693]
 [ 0.07595028 -1.2573844 ]
 [-0.23193759 -1.8107857 ]], shape=(3, 2), dtype=float32)
tf.Tensor(False, shape=(), dtype=bool)


In [43]:
#shuffle the order of elements in a tensor
#it is useful when you want to shuffle your data so the inherent order doesn't affect the learning
not_shuffled = tf.constant([[14, 7],
                            [8, 10],
                            [3, 1]])
shuffled = tf.random.shuffle(not_shuffled)
not_shuffled, shuffled, not_shuffled == shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[14,  7],
        [ 8, 10],
        [ 3,  1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 8, 10],
        [ 3,  1],
        [14,  7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [46]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[14,  7],
       [ 8, 10],
       [ 3,  1]], dtype=int32)>

In [48]:
print(tf.ones([10, 7])) #create tensor of all ones as numpy
print(tf.zeros([3, 4])) #create tensor of all zeros as numpy

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]], shape=(10, 7), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [54]:
#turn numpy array into tensors
#tensor can run on GPU computing while numpy array can't
numpy_A = np.arange(1, 25, dtype=np.int32) #create numpy array with range 1 to 25

A = tf.constant(numpy_A, shape=(2, 3, 4)) #create tensor from numpy array
B = tf.constant(numpy_A) #create tensor from numpy array
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
"""
https://youtu.be/tpCFfeUEGs8?list=PLTcYOxhCH2IB2PBEPRphuTdH4dNgHkVEl&t=6838
"""